module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#22b1ec",
        "inverse-on-surface": "#4d556b",
        "primary-fixed": "#2db7f2",
        "on-tertiary": "#573500",
        "on-tertiary-fixed-variant": "#563400",
        "on-primary": "#00374d",
        "on-primary-container": "#002b3d",
        "secondary-container": "#006c49",
        "on-error-container": "#ffa8a3",
        "on-secondary-container": "#e1ffec",
        "inverse-surface": "#faf8ff",
        "primary-dim": "#05a9e3",
        "on-surface": "#dee5ff",
        "on-background": "#dee5ff",
        "tertiary-dim": "#e79400",
        "secondary-dim": "#58e7ab",
        "surface-dim": "#060e20",
        "tertiary-fixed-dim": "#e79400",
        "surface": "#060e20",
        "surface-tint": "#3bbffa",
        "surface-container-lowest": "#000000",
        "primary": "#3bbffa",
        "outline-variant": "#40485d",
        "secondary": "#69f6b8",
        "on-secondary": "#005a3c",
        "background": "#060e20",
        "secondary-fixed": "#69f6b8",
        "tertiary-container": "#f8a010",
        "on-secondary-fixed-variant": "#006544",
        "tertiary": "#ffb148",
        "error-container": "#9f0519",
        "surface-container-high": "#141f38",
        "secondary-fixed-dim": "#58e7ab",
        "surface-variant": "#192540",
        "inverse-primary": "#00668b",
        "on-secondary-fixed": "#00452d",
        "on-error": "#490006",
        "error": "#ff716c",
        "surface-container-highest": "#192540",
        "surface-container-low": "#091328",
        "error-dim": "#d7383b",
        "surface-container": "#0f1930",
        "on-tertiary-container": "#4a2c00",
        "primary-fixed-dim": "#05a9e3",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed-variant": "#003a50",
        "outline": "#6d758c",
        "on-primary-fixed": "#00121d",
        "surface-bright": "#1f2b49",
        "tertiary-fixed": "#f8a010",
        "on-surface-variant": "#a3aac4"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["Fira Code", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
